gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # time in seconds
    ttl_update: false
    single_use: true
    token_parameter_name: refresh_token
    cookie:
      enabled: true
      same_site: lax              # default value
      path: /                     # default value
      domain: localhost                 # default value
      http_only: true              # default value
      secure: true                 # default value
      remove_token_from_body: true # default value
