export const ScoreBoardsActionTypes = {
    FETCH_SCORE_BOARDS_OF_CHALLENGE_REQUEST: "FETCH_SCORE_BOARDS_OF_CHALLENGE_REQUEST",
    FETCH_SCORE_BOARDS_OF_CHALLENGE_SUCCESS: "FETCH_SCORE_BOARDS_OF_CHALLENGE_SUCCESS",
    FETCH_SCORE_BOARDS_OF_CHALLENGE_ERROR: "FETCH_SCORE_BOARDS_OF_CHALLENGE_ERROR",
}