
export const TidyUserActionTypes = {
    FETCH_TIDY_USER_REQUEST: "FETCH_TIDY_USER_REQUEST",
    FETCH_TIDY_USER_SUCCESS: "FETCH_TIDY_USER_SUCCESS",
    FETCH_TIDY_USER_ERROR: "FETCH_TIDY_USER_ERROR",
    EDIT_TIDY_USER_REQUEST: "EDIT_TIDY_USER_REQUEST",
    EDIT_TIDY_USER_SUCCESS: "EDIT_TIDY_USER_SUCCESS",
    EDIT_TIDY_USER_ERROR: "EDIT_TIDY_USER_ERROR",
    CREATE_TIDY_USER_REQUEST: "CREATE_TIDY_USER_REQUEST",
    CREATE_TIDY_USER_SUCCESS: "CREATE_TIDY_USER_SUCCESS",
    CREATE_TIDY_USER_ERROR: "CREATE_TIDY_USER_ERROR",
    DELETE_TIDY_USER_REQUEST: "DELETE_TIDY_USER_REQUEST",
    DELETE_TIDY_USER_SUCCESS: "DELETE_TIDY_USER_SUCCESS",
    DELETE_TIDY_USER_ERROR: "DELETE_TIDY_USER_ERROR",
}

