export const ModelTasksActionTypes = {
    FETCH_ALL_MODEL_TASKS_REQUEST: "FETCH_ALL_MODEL_TASKS_REQUEST",
    FETCH_ALL_MODEL_TASKS_SUCCESS: "FETCH_ALL_MODEL_TASKS_SUCCESS",
    FETCH_ALL_MODEL_TASKS_ERROR: "FETCH_ALL_MODEL_TASKS_ERROR",
    FETCH_MODEL_TASK_REQUEST: "FETCH_MODEL_TASK_REQUEST",
    FETCH_MODEL_TASK_SUCCESS: "FETCH_MODEL_TASK_SUCCESS",
    FETCH_MODEL_TASK_ERROR: "FETCH_MODEL_TASK_ERROR",
    CREATE_MODEL_TASK_REQUEST: "CREATE_MODEL_TASK_REQUEST",
    CREATE_MODEL_TASK_SUCCESS: "CREATE_MODEL_TASK_SUCCESS",
    CREATE_MODEL_TASK_ERROR: "CREATE_MODEL_TASK_ERROR",
    DELETE_MODEL_TASK_REQUEST: "DELETE_MODEL_TASK_REQUEST",
    DELETE_MODEL_TASK_SUCCESS: "DELETE_MODEL_TASK_SUCCESS",
    DELETE_MODEL_TASK_ERROR: "DELETE_MODEL_TASK_ERROR",
    EDIT_MODEL_TASK_REQUEST: "EDIT_MODEL_TASK_REQUEST",
    EDIT_MODEL_TASK_SUCCESS: "EDIT_MODEL_TASK_SUCCESS",
    EDIT_MODEL_TASK_ERROR: "EDIT_MODEL_TASK_ERROR"
}