export const HomeMembersActionTypes = {
    FETCH_ALL_HOME_MEMBERS_REQUEST: "FETCH_ALL_HOME_MEMBERS_REQUEST",
    FETCH_ALL_HOME_MEMBERS_SUCCESS: "FETCH_ALL_HOME_MEMBERS_SUCCESS",
    FETCH_ALL_HOME_MEMBERS_ERROR: "FETCH_ALL_HOME_MEMBERS_ERROR",
    FETCH_HOME_MEMBER_REQUEST: "FETCH_HOME_MEMBER_REQUEST",
    FETCH_HOME_MEMBER_SUCCESS: "FETCH_HOME_MEMBER_SUCCESS",
    FETCH_HOME_MEMBER_ERROR: "FETCH_HOME_MEMBER_ERROR",
    CREATE_HOME_MEMBER_REQUEST: "CREATE_HOME_MEMBER_REQUEST",
    CREATE_HOME_MEMBER_SUCCESS: "CREATE_HOME_MEMBER_SUCCESS",
    CREATE_HOME_MEMBER_ERROR: "CREATE_HOME_MEMBER_ERROR",
    DELETE_HOME_MEMBER_REQUEST: "DELETE_HOME_MEMBER_REQUEST",
    DELETE_HOME_MEMBER_SUCCESS: "DELETE_HOME_MEMBER_SUCCESS",
    DELETE_HOME_MEMBER_ERROR: "DELETE_HOME_MEMBER_ERROR",
    EDIT_HOME_MEMBER_REQUEST: "EDIT_HOME_MEMBER_REQUEST",
    EDIT_HOME_MEMBER_SUCCESS: "EDIT_HOME_MEMBER_SUCCESS",
    EDIT_HOME_MEMBER_ERROR: "EDIT_HOME_MEMBER_ERROR"
}