export const ChallengeListActionTypes = {
    FETCH_ALL_CHALLENGES_REQUEST: "FETCH_ALL_CHALLENGES_REQUEST",
    FETCH_ALL_CHALLENGES_SUCCESS: "FETCH_ALL_CHALLENGES_SUCCESS",
    FETCH_ALL_CHALLENGES_ERROR: "FETCH_ALL_CHALLENGES_ERROR",
}